Revert "ci: 🤖 always run percy"
This reverts commit 2d04c402a23dc3193beca8db2b27e02871fa61c9.

diff --git a/.github/src/workflows/test-and-deploy.yml b/.github/src/workflows/test-and-deploy.yml
--- a/.github/src/workflows/test-and-deploy.yml
+++ b/.github/src/workflows/test-and-deploy.yml
@@ -91,15 +91,26 @@ jobs:
       - name: Increase file watchers to avoid storybook warnings
         run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
 
+        # Check if we should run e2e tests & percy review.
+        # If no tests are ran or if we don't take any snapshots,
+        # percy will fail.
+      - name: Should run E2E?
+        id: should-run-e2e
+        run: |
+          # `grep -c` fails if list is empty (no e2e tests to run)
+          SHOULD_RUN_E2E=$(yarn nx print-affected --base=deployed/marmicode-next \
+            | yarn json projects | grep -c e2e && echo true || echo false)
+          echo "::set-output name=should-run-e2e::$SHOULD_RUN_E2E"
+
       # Run all E2E tests on main branch.
       - name: All E2E
-        if: github.ref == 'refs/heads/main'
+        if: github.ref == 'refs/heads/main' && steps.should-run-e2e.outputs.should-run-e2e != false
         run: npx @percy/cli exec -- $(npm bin)/nx run-many --all --target=e2e --base=deployed/marmicode-next --browser=chrome
 
       # Run affected E2E tests only on other branches.
       # Cf. https://docs.percy.io/docs/partial-builds
       - name: Affected E2E
-        if: github.ref != 'refs/heads/main'
+        if: github.ref != 'refs/heads/main' && steps.should-run-e2e.outputs.should-run-e2e != false
         run: npx @percy/cli exec -- $(npm bin)/nx affected --target=e2e --base=deployed/marmicode-next --browser=chrome
         env:
           PERCY_PARTIAL_BUILD: 1
